routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ItemController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});;

Route::get('/add-menu',[MenuController::class,'addMenu'])->name('menus.add');

//For storing an image
Route::post('/store-menu',[MenuController::class,'storeMenu'])->name('menus.store');

//For showing an image
Route::get('/view-menu',[MenuController::class,'viewMenu'])->name('menus.view');

Route::get('/update-menu',[MenuController::class,'update'])->name('menus.update');
Route::resource('menu',MenuController::class);



//Shop//////

Route::get('/add-shop',[ShopController::class,'addShop'])->name('shops.add');

Route::post('/store-shop',[ShopController::class,'storeShop'])->name('shops.store');

Route::get('/view-shop',[ShopController::class,'viewShop'])
->name('shops.view');

Route::resource('shop',ShopController::class);


//Route for item
Route::get('/add-item',[ItemController::class,'addItem'])->name('items.add');

Route::post('/store-item',[ItemController::class,'storeItem'])->name('items.store');

Route::get('/view-item',[ItemController::class,'viewItem'])
->name('items.view');

Route::resource('item',ItemController::class);

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $fillable =['name','cover','image','price','menu_id','shop_id'];


    public function menu() {
        return $this->belongsTo(Menu::class);
    }

    public function shop(){
        return $this->belongsTo(Shop::class);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Item;
use App\Models\Menu;
use App\Models\Shop;

class ItemController extends Controller
{
    public function addItem(){
        $menus = Menu::all();
        $shops = Shop::all();
        return view('item.add_item')->with([
            'menus' => $menus,
            'shops' => $shops
        ]);
    }

    public function storeItem(Request $request){
            $data = new Item();
            $data['name'] = $request->name;

            if($request->file('cover')){
                $file= $request->file('cover');
                $path="storage/images/item/";
                $filename=date('YmdHi').$file->getClientOriginalName();
                $file->storeAs('public/images/item/',$filename);
            
               // $file-> move(public_path('public/Image'), $filename);
                $data['cover']= $path.$filename;
            }

            if($request->file('images')){
                $files= $request->file('images');

                foreach($files as $file){

                    $filename=date('YmdHi').$file->getClientOriginalName();              
                    $path="storage/images/item/";
                    $file->storeAs('public/images/item/',$filename);
                    $imgs[]=$path.$filename;
                }

                $imgstr = implode(", ",$imgs);
                $data['image']=$imgstr;  
            
               // $file-> move(public_path('public/Image'), $filename);
                
            }

            $data['price']=$request->price;
            $data['shop_id']=$request->shop_id;
            $data['menu_id']=$request->menu_id;
            $data->save();

            return redirect()->route('items.view');


    }

    public function viewItem(){
        $imageData= Item::all();
        // dd($imageData);
        return view('item.view_item',compact('imageData'));
    }

    public function edit(item $item){
        $menus = Menu::all();
        $shops = Shop::all();
        return view('item.edit',['item'=>$item])->with([
            'menus' => $menus,
            'shops' => $shops
        ]); 
        // return view('item.edit',['item'=>$item]);
    }

    public function update(Request $request,Item $item){
        
        $inputs = $request->all();
        $image = null;
        $cover= null;
        if(isset($inputs['new_cover'])) {
            if($request->file('new_cover')){
                $file= $request->file('new_cover');
                $path="storage/images/item/";
                $filename=date('YmdHi').$file->getClientOriginalName();
                $file->storeAs('public/images/item/',$filename);
                $cover = $path.$filename;

                if(file_exists($item->image)){
                    unlink($item->image);
                }
                 
            }
        }else{
            $cover = $inputs['old_cover'];
        }

        if(isset($inputs['newimages'])) {
            if($request->file('newimages')){
                $files= $request->file('newimages');
                foreach($files as $file){
                    $filename=date('YmdHi').$file->getClientOriginalName();
                    $path="storage/images/item/";
                    $file->storeAs('public/images/item/',$filename);
                    $img[]= $path.$filename;
                }
                    
                $image=implode(", ",$img);
                
                if(file_exists($item->image)){
                    unlink($item->image);
                }
            }
        }else{
            $image = $inputs['oldimages'];
        }



        $item->name=$inputs['name'];
        $item->price=$inputs['price'];
        $item->cover=$cover;
        $item->image=$image;
        $item->shop_id=$inputs['shop_id'];
        $item->menu_id=$inputs['menu_id'];
        $item->save();
        return redirect()->route('items.view')->with('success','successfully Updated');
    }
    
    public function destroy(Item $item){
            $item->delete();
            return redirect()->route('items.view')->with('success','Successfully deleted');
    }
}

resources/views/item/add_item.blade.php
@extends('welcome')

@section('content')


<div class="container">
  <form method="post" action="{{ route('items.store') }}" 
		enctype="multipart/form-data">
    @csrf

    <div class="name">
        <label><h4>Add Name</h4></label>
        <input type="text" class="form-control" required name="name">
    </div><br>

    <div class="cover">
      <label><h4>Add Cover</h4></label>
      <input type="file" class="form-control" required name="cover">
    </div><br>

    <div class="image">
      <label><h4>Add Image</h4></label>
      <input type="file" class="image" required name="images[]" multiple>
    </div><br>

    <div class="price">
        <label><h4>Add Price</h4></label>
        <input type="text" class="form-control" required name="price">
    </div><br>

    <div class="shop_c">
      <label><h4>Shop</h4></label>
      <select name="shop_id" class="form-control">
        <option value=" " disabled selected>--Select Shop--</option>
      @foreach($shops as $shop)
        <option value="{{$shop->id}}" >{{$shop->name ?? ''}}</option>
        @endforeach
      </select> 
    </div><br>

    <div class="menu_c">
      <label><h4>Menu</h4></label>
      <select name="menu_id" class="form-control">
        <option value=" " disabled selected>--Select Menu--</option>
      @foreach($menus as $menu)
        <option value="{{$menu->id}}" >{{$menu->name ?? ''}}</option>
        @endforeach
      </select> 
    </div><br>

    



    <div class="post_button">
      <button type="submit" class="btn btn-success">Add</button>
    </div>
  </form>
</div>

resources/views/item/edit.blade.php
@extends('welcome')

@section('content')


<div class="container">
  <form method="post" action="{{route('item.update',$item->id)}}"  
		enctype="multipart/form-data">
    @csrf
    @method('PUT')

    <div class="name">
        <label><h4>Add Name</h4></label>
        <input type="text" class="form-control" value="{{$item->name}}" name="name">
    </div><br>

    <div class="cover">
      <label><h4>Old Cover</h4></label>
      <input type="hidden"  name="old_cover" value="{{$item->cover}}">
      <img src="{{asset($item->cover)}}" width="100px">
    </div><br>

    <div class="cover">
      <label><h4>New Cover</h4></label>
      <input type="file" class="form-control"  name="new_cover">
    </div><br>

    <div class="image">
      <label><h4>Old Image</h4></label>
      <input type="hidden" class="image"  name="oldimages[]" value="{{$item->image}}" multiple>
      @foreach(explode(', ',$item->image) as $path)
      <img src="{{asset($path)}}" width="100px">
     @endforeach
    </div><br>

    <div class="image">
      <label><h4>New Image</h4></label>
      <input type="file" class="image"  name="newimages[]"  multiple>
      
    </div><br>

    <div class="price">
        <label><h4>Add Price</h4></label>
        <input type="text" class="form-control" value="{{$item->price}}" name="price">
    </div><br>

    <div class="shop_c">
      <label><h4>Shop</h4></label>
      <select name="shop_id" class="form-control">
        <option value=" " disabled selected>--Select Shop--</option>
      @foreach($shops as $shop)
        <option  @if($shop->id==$item->shop_id) selected="selected"
                @endif
        value="{{$shop->id}}" >{{$shop->name ?? ''}}</option>
        @endforeach
      </select> 
    </div><br>

    <div class="menu_c">
      <label><h4>Menu</h4></label>
      <select name="menu_id" class="form-control">
        <option value=" " disabled selected>--Select Menu--</option>
      @foreach($menus as $menu)
        <option @if($menu->id==$item->menu_id) selected="selected"
                @endif
        value="{{$menu->id}}" >{{$menu->name ?? ''}}</option>
        @endforeach
      </select> 
    </div><br>

    <div class="post_button">
      <button type="submit" class="btn btn-success">Add</button>
    </div>
  </form>
</div>

resources/views/item/view_item.blade.php
@extends('welcome')

@section('content')

<div class="container">
    <h3>View all items</h3><hr>

    <a class="btn btn-success" href="{{route('items.add')}}" style="text-decoration:none;padding:10px;">
            Create Items +
          </a>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Item ID</th>
          <th scope="col">Name</th>
          <th scope="col">Cover</th>
          <th scope="col">Image</th>
          <th scope="col">Price</th>
          <th scope="col">Menu</th>
          <th scope="col">Shop</th>
          <th scope="col">Action</th>

        </tr>
      </thead>
      <tbody>
        @foreach($imageData as $data)
        <tr>
            <td>{{$data->id}}</td>

            <td>
                {{$data->name}}
            </td>  

            <td>
            <img src="{{asset($data->cover)}}"
            style="height: 100px; width:100px;">
	        </td> 

            <td>

            @foreach(explode(', ', $data->image) as $path)
            <img src="{{asset($path)}}" style="height: 100px; width: 150px;">
            @endforeach
           
	        </td> 

            <td>
            {{$data->price}}
            </td> 

            <td>
                {{$data->menu->name ?? 'unknown'}}
            </td> 

            <td>
                {{$data->shop->name ?? 'unknown'}}
            </td>

            <td>

                <a href="{{route('item.edit',$data->id)}}" class="btn btn-primary">Edit</a>
                
                <form action="{{route('item.destroy',$data->id)}}" method="POST">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger">
                      DELETE
                  </button>
                </form>
            </td>
            
        </tr>
      @endforeach
      </tbody>
    </table>
  </div>