routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ItemController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});;

Route::get('/add-menu',[MenuController::class,'addMenu'])->name('menus.add');

//For storing an image
Route::post('/store-menu',[MenuController::class,'storeMenu'])->name('menus.store');

//For showing an image
Route::get('/view-menu',[MenuController::class,'viewMenu'])->name('menus.view');

Route::get('/update-menu',[MenuController::class,'update'])->name('menus.update');
Route::resource('menu',MenuController::class);



//Shop//////

Route::get('/add-shop',[ShopController::class,'addShop'])->name('shops.add');

Route::post('/store-shop',[ShopController::class,'storeShop'])->name('shops.store');

Route::get('/view-shop',[ShopController::class,'viewShop'])
->name('shops.view');

Route::resource('shop',ShopController::class);


//Route for item
Route::get('/add-item',[ItemController::class,'addItem'])->name('items.add');

Route::post('/store-item',[ItemController::class,'storeItem'])->name('items.store');

Route::get('/view-item',[ItemController::class,'viewItem'])
->name('items.view');

Route::resource('item',ItemController::class);

app/Models/Shop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shop extends Model
{
    use HasFactory;
    protected $fillable=['name','address','logo'];

    public function item() {
        return $this->hasMany(Item::class);
    }
}

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Shop;

class ShopController extends Controller
{

    public function addShop(){
        return view('shop.add_shop');
    }
    
    public function storeShop(Request $request){
        $data= new Shop();

         $data['name'] =  $request->name ;
         $data['address'] =  $request->address ;
        if($request->file('logo')){
            $file= $request->file('logo');
            $path="storage/images/logo/";
            $filename= date('YmdHi').$file->getClientOriginalName();
            // $file-> move(public_path('public/Image'), $filename);
            $file->storeAs('public/images/logo/',$filename);
            $data['logo']= $path.$filename;
        }

        $data->save();
        return redirect()->route('shops.view');
    }
		//View image
    public function viewShop(){
        $imageData= Shop::all();
        return view('shop.view_shop',compact('imageData'));
    }

    public function edit(Shop $shop){
        return view('shop.edit',['shop'=>$shop]);
    }

    public function update(Request $request,Shop $shop){
        $inputs=$request->all();
        $image=null;
        if(isset($inputs['new_logo'])){
            if($request->file('new_logo')){
                $file= $request->file('new_logo');
                $path="storage/images/logo/";
                $filename= date('YmdHi').$file->getClientOriginalName();
                // $file-> move(public_path('public/Image'), $filename);
                $file->storeAs('public/images/logo/',$filename);
                
                $image= $path.$filename;
                
                if(file_exists($shop->image)) {
                    
                    unlink($shop->image);
                }
            }

        }else{
            $image = $inputs['old_logo'];
        }
        
        $shop->name=$inputs['name'];
        $shop->address=$inputs['address'];
        $shop->logo=$image;
        $shop->save();
        return redirect()->route('shops.view')->with('success','successfully Updated');
    }

    
    public function destroy(Shop $shop){
            $shop->delete();
            return redirect()->route('shops.view')->with('success','Sucessfully Deleted');
    }
    
    
}

resources/views/shop/add_shop.blade.php
@extends('welcome')

@section('content')


<div class="container">
  <form method="post" action="{{ route('shops.store') }}" 
		enctype="multipart/form-data">
    @csrf
   
    <div class="name">
        <label><h4>Add Name</h4></label>
        <input type="text" class="form-control" required name="name">
    </div><br>

    <div class="logo">
      <label><h4>Logo</h4></label>
      <input type="file" class="form-control" required name="logo">
    </div>

    <div class="address">
      <label><h4>Address</h4></label>
      <input type="text" class="form-control" required name="address">
    </div>

    <div class="post_button">
      <button type="submit" class="btn btn-success">Add</button>
    </div>
  </form>
</div>

resources/views/shop/edit.blade.php
@extends('welcome')
@section('content')

<div class="container">
  <form method="post" action="{{ route('shop.update',$shop->id) }}" 
		enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="name">
        <label><h4>Add Name</h4></label>
        <input type="text" class="form-control" value="{{$shop->name}}" name="name">
    </div><br>

    <div class="logo">
      <label><h4>Old Logo</h4></label>
      <input type="hidden" name="old_logo" value="{{$shop->logo}}">
      <img src="{{asset($shop->logo)}}" width="100px">
    </div>

    <div class="logo">
      <label><h4>New Logo</h4></label>
      <input type="file" class="form-control" name="new_logo">
    </div>

    <div class="address">
      <label><h4>Address</h4></label>
      <input type="text" class="form-control" value="{{$shop->address}}" name="address">
    </div>

    <div class="post_button">
      <button type="submit" class="btn btn-success">Add</button>
    </div>
  </form>
</div>

resources/views/shop/view_shop.blade.php
@extends('welcome')

@section('content')

<div class="container">
    <h3>View all image</h3><hr>

    <a class="btn btn-success" href="{{route('shops.add')}}" style="text-decoration:none;padding:10px;">
            Create Shop +
          </a>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Image id</th>
          <th scope="col">Name</th>
          <th scope="col">Address</th>
          <th scope="col">Logo</th>
          <th scope="col">Action</th>

        </tr>
      </thead>
      <tbody>
        @foreach($imageData as $data)
        <tr>
          <td>{{$data->id}}</td>

            <td>
                {{$data->name}}
            </td>  

            <td>
                {{$data->address}}
            </td> 

            <td>       
            <!-- <img src="{{url('public/Image/'.$data->logo)}}" -->
            <img src="{{ asset($data->logo) }}"
            style="height: 100px; width: 100px;">
	          </td> 

            <td>

              <a href="{{route('shop.edit',$data->id)}}" class="btn btn-primary">Edit</a>        
              <form action="{{route('shop.destroy',$data->id)}}" method="POST">
              <button class="btn btn-danger">
                  @csrf
                  @method('DELETE')
                Delete
              </button>
              </form>
              
            </td>
        
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>