routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ItemController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});;

Route::get('/add-menu',[MenuController::class,'addMenu'])->name('menus.add');

//For storing an image
Route::post('/store-menu',[MenuController::class,'storeMenu'])->name('menus.store');

//For showing an image
Route::get('/view-menu',[MenuController::class,'viewMenu'])->name('menus.view');

Route::get('/update-menu',[MenuController::class,'update'])->name('menus.update');
Route::resource('menu',MenuController::class);



//Shop//////

Route::get('/add-shop',[ShopController::class,'addShop'])->name('shops.add');

Route::post('/store-shop',[ShopController::class,'storeShop'])->name('shops.store');

Route::get('/view-shop',[ShopController::class,'viewShop'])
->name('shops.view');

Route::resource('shop',ShopController::class);


//Route for item
Route::get('/add-item',[ItemController::class,'addItem'])->name('items.add');

Route::post('/store-item',[ItemController::class,'storeItem'])->name('items.store');

Route::get('/view-item',[ItemController::class,'viewItem'])
->name('items.view');

Route::resource('item',ItemController::class);

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    protected $fillable=['name','image'];

    public function item() {
        return $this->hasMany(Item::class);
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Menu;

class MenuController extends Controller
{
    public function addMenu(){
        return view('menu.add_menu');
    }
    
    public function storeMenu(Request $request){
        $data= new Menu();
        if($request->file('image')){
            $file= $request->file('image');
            $path="storage/images/menu/";
            $filename=date('YmdHi').$file->getClientOriginalName();
            $file->storeAs('public/images/menu/',$filename);
        
           // $file-> move(public_path('public/Image'), $filename);
            $data['image']= $path.$filename;
        }

        $data['name'] =  $request->name ;
        $data->save();

       
        return redirect()->route('menus.view');
    }
		//View image
    public function viewMenu(){
        $imageData= Menu::all();
        return view('menu.view_menu',compact('imageData'));
    }

    public function edit(Menu $menu){
        return view('menu.edit',['menu'=>$menu]);
    }

    public function update(Request $request,Menu $menu){
        // dd($request);
        $inputs = $request->all(); 
        $image = null;
        if(isset($inputs['new_image'])) {
            if($request->file('new_image')){
                $file= $request->file('new_image');
                $path="storage/images/menu/";
                $filename=date('YmdHi').$file->getClientOriginalName();
                $file->storeAs('public/images/menu/',$filename);
            
               // $file-> move(public_path('public/Image'), $filename);

                $image= $path.$filename;
                
                if(file_exists($menu->image)) {
                    
                    unlink($menu->image);
                }
                
            }
    
        }else{
            $image = $inputs['old_image'];
        }

        $menu->name = $inputs['name'];
        $menu->image = $image;
        $menu->save();
        return redirect()->route('menus.view')->with('success','successfully Updated');
    }

    public function destroy(Menu $menu){
        $menu->delete();
        return redirect()->route('menus.view')->with('success','Successfully deleted');
    }

    
}

resources/views/menu/add_menu.blade.php
@extends('welcome')

@section('content')


<div class="container">
  <form method="post" action="{{ route('menus.store') }}" 
		enctype="multipart/form-data">
    @csrf
    <div class="image">
      <label><h4>Add image</h4></label>
      <input type="file" class="form-control"  name="image">
    </div>

    <div class="name">
        <label><h4>Add Name</h4></label>
        <input type="text" class="form-control"  name="name">
    </div><br>

    <div class="post_button">
      <button type="submit" class="btn btn-success">Add</button>
    </div>
  </form>
</div>

resources/views/menu/edit.blade.php
@extends('welcome')

@section('content')


<div class="container">
  <form method="post" action="{{route('menu.update',$menu->id)}}" 
		enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="image">
      <label><h4>Old image</h4></label>
      <br>
      <input type="hidden" name="old_image" value="{{$menu->image}}" />
      <img src="{{asset($menu->image)}}" width="100px">
    </div>
 
    <div class="new_image">
      <label><h4>New image</h4></label>
      <input type="file" class="form-control"  name="new_image"><br>
    </div>

    <div class="name">
        <label><h4>Add Name</h4></label>
        <input type="text" class="form-control" value="{{$menu->name}}" name="name">
    </div><br>

    <div class="post_button">
      <button type="submit" class="btn btn-success">Add</button>
    </div>
  </form>
</div>

resources/views/menu/view_menu.blade.php
@extends('welcome')

@section('content')

@section('script')
<div class="container">
    <h3>View all image</h3><hr>
    <table class="table">
      <thead>

        <tr>
          <button>
          <a class="btn btn-success" href="{{route('menus.add')}}" style="text-decoration:none;padding:10px;">
            Create Menu +
          </a>
          </button>
          
        </tr>
        <tr>
          <th scope="col">Image id</th>
          <th scope="col">Image</th>
          <th scope="col">Name</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach($imageData as $data)
        <tr>
          <td>{{$data->id}}</td>
          <td>
            <img src="{{ asset($data->image) }}"
            style="height: 100px; width: 150px;">
	        </td> 
            <td>
                {{$data->name}}
            </td>
            <td>
                <a href="{{route('menu.edit',$data->id)}}" class="btn btn-primary">Edit</a>

                <form action="{{route('menu.destroy',$data->id)}}" method="POST">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" onclick="return confirm('Are you sure to delete?')">
                    Delete
                  </button>
                </form>

            </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>

  


  